### ISSUE TITLE
IncompleteRead TwitterConnectionError

### ISSUE THREAD

**Issue by libbyh** [casmlab/purpletag#20]
Using --track option
Running for a couple days
```
WARNING:root:<class 'requests.packages.urllib3.exceptions.ProtocolError'> ('Connection broken: IncompleteRead(0 bytes read, 1 more expected)', IncompleteRead(0 bytes read, 1 more expected))
Traceback (most recent call last):
  File "/home/libbyh/anaconda3/envs/purpletag/bin/purpletag-collect", line 11, in <module>
    load_entry_point('purpletag==0.1.4', 'console_scripts', 'purpletag-collect')()
  File "/home/libbyh/anaconda3/envs/purpletag/lib/python2.7/site-packages/purpletag-0.1.4-py2.7.egg/purpletag/purpletag_collect.py", line 84, in main
    track_users(ids)
  File "/home/libbyh/anaconda3/envs/purpletag/lib/python2.7/site-packages/purpletag-0.1.4-py2.7.egg/purpletag/purpletag_collect.py", line 40, in track_users
    for tweet in twutil.collect.track_user_ids(ids):
  File "/home/libbyh/anaconda3/envs/purpletag/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line 305, in __iter__
    for item in self._iter_stream():
  File "/home/libbyh/anaconda3/envs/purpletag/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line 294, in _iter_stream
    raise TwitterConnectionError(e)
TwitterAPI.TwitterError.TwitterConnectionError: ('Connection broken: IncompleteRead(0 bytes read, 1 more expected)', IncompleteRead(0 bytes read, 1 more expected))
```

**Comment by libbyh** [comment]
Looks like [suggestion is to suppress the error and keep going](https://stackoverflow.com/questions/28717249/error-while-fetching-tweets-with-tweepy), but then we'd lose tweets. Alternative is to queue any processing so we don't fall behind. Not sure what that would look like since there's nearly-minimal processing already.

**Comment by aronwc** [comment]
Right; writing to disk is slow, particularly if it's not a solid state drive. Thus, ingestion of tweets blocks while writing is happening. I suppose this can happen during times of peak tweeting, or also if there are some other jobs running on the same machine doing a lot of disk reads/writes.

One approach to the "queue" solution is to have a separate process handle the writing:
https://stackoverflow.com/a/16214889

The writing process should eventually "catch up" and clear its queue when the tweet volume dies down.
